create or replace view DEV.SBOX_SHILTON.CARDUP_B2B_SG_USERID_F30DMAKE_F30DCOLLECT_AMOUNT as
with
    MAKE_FIRSTTX_TABLE as (
        select
            CARDUP_PAYMENT_USER_ID USER_ID,
            MIN(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) MAKE_FIRSTTX_DATE,
            MIN(DATEADD(day, 30, CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) MAKE_FIRSTTX_DATE_30DAY
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T
        where
            CARDUP_PAYMENT_USER_TYPE = 'business'
            and CARDUP_PAYMENT_STATUS NOT IN ('Payment Failed', 'Cancelled', 'Refunded', 'Refunding')
            and CARDUP_PAYMENT_CU_LOCALE_ID = 1
        group by
            1
    ),
    MAKE_F30D_PAY_TABLE as (
        select
            PAY_TABLE.CARDUP_PAYMENT_USER_ID USER_ID,
            PAY_TABLE.CARDUP_PAYMENT_PAYMENT_TYPE CARDUP_PAYMENT_PAYMENT_TYPE_MAKE,
            SUM(CARDUP_PAYMENT_USD_AMT) FIRST_30D_PAYMENT_AMOUNT_MAKE
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T PAY_TABLE
            join MAKE_FIRSTTX_TABLE ONBOARD_TABLE on PAY_TABLE.CARDUP_PAYMENT_USER_ID = ONBOARD_TABLE.USER_ID
            and PAY_TABLE.CARDUP_PAYMENT_SUCCESS_AT_UTC_TS >= ONBOARD_TABLE.MAKE_FIRSTTX_DATE
            and PAY_TABLE.CARDUP_PAYMENT_SUCCESS_AT_UTC_TS <= ONBOARD_TABLE.MAKE_FIRSTTX_DATE_30DAY
        where
            PAY_TABLE.CARDUP_PAYMENT_USER_TYPE = 'business'
        group by
            1,
            2
    ),
    COLLECT_FIRSTTX_TABLE as (
        select
            CARDUP_PAYMENT_USER_ID USER_ID,
            MIN(CARDUP_PAYMENT_SUCCESS_AT_UTC_TS) COLLECT_FIRSTTX_DATE,
            MIN(DATEADD(day, 30, CARDUP_PAYMENT_SUCCESS_AT_UTC_TS)) COLLECT_FIRSTTX_DATE_30DAY
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T
        where
            CARDUP_PAYMENT_USER_TYPE = 'guest'
            and CARDUP_PAYMENT_STATUS NOT IN ('Payment Failed', 'Cancelled', 'Refunded', 'Refunding')
            and CARDUP_PAYMENT_CU_LOCALE_ID = 1
        group by
            1
    ),
    COLLECT_F30D_PAY_TABLE as (
        select
            PAY_TABLE.CARDUP_PAYMENT_USER_ID USER_ID,
            PAY_TABLE.CARDUP_PAYMENT_PAYMENT_TYPE CARDUP_PAYMENT_PAYMENT_TYPE_COLLECT,
            SUM(CARDUP_PAYMENT_USD_AMT) FIRST_30D_PAYMENT_AMOUNT_COLLECT
        from
            ADM.TRANSACTION.CARDUP_PAYMENT_DENORM_T PAY_TABLE
            join COLLECT_FIRSTTX_TABLE ONBOARD_TABLE on PAY_TABLE.CARDUP_PAYMENT_USER_PAYEE_ID = ONBOARD_TABLE.USER_ID
            and PAY_TABLE.CARDUP_PAYMENT_SUCCESS_AT_UTC_TS >= ONBOARD_TABLE.COLLECT_FIRSTTX_DATE
            and PAY_TABLE.CARDUP_PAYMENT_SUCCESS_AT_UTC_TS <= ONBOARD_TABLE.COLLECT_FIRSTTX_DATE_30DAY
        where
            PAY_TABLE.CARDUP_PAYMENT_USER_TYPE = 'guest'
        group by
            1,
            2
    )
select
    USER_ID,
    CARDUP_PAYMENT_PAYMENT_TYPE_MAKE,
    CARDUP_PAYMENT_PAYMENT_TYPE_COLLECT,
    FIRST_30D_PAYMENT_AMOUNT_MAKE,
    FIRST_30D_PAYMENT_AMOUNT_COLLECT
from
    COLLECT_F30D_PAY_TABLE
    full outer join MAKE_F30D_PAY_TABLE using (USER_ID);