select
    T1.ID,
    T2.CBM_COMPOSITE_ID
from
    DEV.SBOX_SHILTON.CONTACT_OWNERS_HISTORICAL T1
    join CBM.CARDUP_DB_REPORTING.USER_UTM T2 on T1.ID = T2.HUBSPOT_CONTACT_ID;

select
    *
from
    DEV.SBOX_SHILTON.CONTACT_OWNERS_HISTORICAL
limit
    10;
