select distinct
    SALES_OWNER
from
    CBM.CARDUP_DB_REPORTING.USER_DATA;

select
    *
from
    CBM.CARDUP_DB_REPORTING.USER_DATA
limit
    10;

select
    *
from
    DEV.SBOX_SHILTON.CONTACT_OWNERS_HISTORICAL_UNPIVOT
limit
    10;

select
    CAST(T1.HUBSPOT_CONTACT_ID as INT) RECORD_ID,
    CASE
        WHEN SUBSTRING(T1.ACCOUNT_NUMBER, 1, 2) != 'CU' THEN NULL
        ELSE CAST(SUBSTRING(T1.ACCOUNT_NUMBER, 3) AS INT)
    END USER_ID,
    T3.COMPANY_ID,
    TRY_TO_TIMESTAMP(T1.HUBSPOT_CREATED_DATE) HUBSPOT_CREATED_DATE,
    T1.BECAME_INTERESTED_IN_COLLECT_DATE,
    T2.SALES_OWNER
from
    CBM.CARDUP_DB_REPORTING.USER_UTM T1
    left outer join CBM.CARDUP_DB_REPORTING.USER_DATA T2 on CASE
        WHEN SUBSTRING(T1.ACCOUNT_NUMBER, 1, 2) != 'CU' THEN NULL
        ELSE CAST(SUBSTRING(T1.ACCOUNT_NUMBER, 3) AS INT)
    END = T2.USER_ID
    left outer join CBM.CARDUP_DB_REPORTING.COMPANY_DATA T3 on T2.COMPANY_ID = T3.COMPANY_ID
where
    T1.HUBSPOT_CREATED_DATE is not null
    and T1.CU_LOCALE_ID = 1;

select
    APPROX_PERCENTILE(DAYS_SIGN_UP_TO_ONBOARDED_MAKE, 0.5) as MEDIAN
from
    DEV.SBOX_SHILTON.CARDUP_B2B_SG_FUNNEL_WITH_HISTORICAL_TAGGING
where
    DATE_TRUNC(MONTH, DATE(HS_CREATE_DATE)) = DATE('2024-09-01')
    and DAYS_SIGN_UP_TO_ONBOARDED_MAKE is not null
    and (
        LOWER(CONTACT_OWNER) LIKE '%keegan%'
        or LOWER(CONTACT_OWNER_HISTORICAL) LIKE '%keegan%'
        or LOWER(CONTACT_OWNER_FROM_DWH) LIKE '%keegan%'
        or LOWER(CONTACT_OWNER) LIKE '%leia%'
        or LOWER(CONTACT_OWNER_HISTORICAL) LIKE '%leia%'
        or LOWER(CONTACT_OWNER_FROM_DWH) LIKE '%leia%'
        or LOWER(CONTACT_OWNER) LIKE '%jon%'
        or LOWER(CONTACT_OWNER_HISTORICAL) LIKE '%jon%'
        or LOWER(CONTACT_OWNER_FROM_DWH) LIKE '%jon%'
    );